/* 由 LBLB 数学前沿更新器自动生成：各主题最新论文（arXiv 优先，Semantic Scholar 备用）。请勿手动编辑。 */
window.LBLB_PAPERS = {
 "数论": [
  {
   "title": "On Greenberg's conjecture for rational elliptic curves at Eisenstein primes",
   "link": "https://arxiv.org/abs/2609.40282v1",
   "abs": "Let $E/\\mathbb{Q}$ be an elliptic curve, and let $p$ be an odd prime of ordinary reduction for $E$, and assume that $E$ admits a rational $p$-isogeny. In this paper we prove Greenberg's conjecture on the vanishing of…",
   "date": "2026-09-30",
   "author": "Zichao Lin"
  },
  {
   "title": "Resurgent rigidity of mock theta functions: uniqueness and natural boundary crossing",
   "link": "https://arxiv.org/abs/2609.40276v1",
   "abs": "We develop a resurgent transseries approach to mock theta functions and show that the associated Mordell--Appell integrals underlie their modular and resurgent structure. From these integrals, we recover the modular…",
   "date": "2026-09-30",
   "author": "Ovidiu Costin"
  },
  {
   "title": "A proof of Hirose's duality conjecture",
   "link": "https://arxiv.org/abs/2609.40213v1",
   "abs": "Hirose formulated a duality conjecture for a $q$-discretization of iterated integrals on the four-punctured projective line, incorporating word-dependent $q$-shifts of the parameters. In this paper, we prove this…",
   "date": "2026-09-30",
   "author": "Shin-ichiro Seki"
  },
  {
   "title": "Semi-stable models, local heights and quadratic Chabauty for $X_0(N)^*$",
   "link": "https://arxiv.org/abs/2609.40207v1",
   "abs": "Quadratic Chabauty computations for $X_0(N)^*$ are complicated by local height contributions at primes of bad reduction. For squarefree $N$, we explain a strategy for constructing a global $p$-adic height for which all…",
   "date": "2026-09-30",
   "author": "Nikola Adžaga"
  },
  {
   "title": "Galois groups of random polynomials of large degree",
   "link": "https://arxiv.org/abs/2609.40123v1",
   "abs": "We study random polynomials of the form $R(x)=x^n+ω_{n-1}x^{n-1}+\\cdots+ω_0$, where $ω_0,\\dots,ω_{n-1}$ are independent, uniformly bounded integer-valued random variables, and $ω_1,\\dots,ω_{n-1}$ have a fixed common law…",
   "date": "2026-09-30",
   "author": "Guy Blachar"
  }
 ],
 "几何": [
  {
   "title": "Positive cubature on $S^2$:low-degree rigidity and uniform bounds",
   "link": "https://arxiv.org/abs/2609.40210v1",
   "abs": "Let \\(N_t\\) denote the least number of nodes in a positive cubature formula of degree \\(t\\) on \\(S^2\\). We prove that a formula of degree \\(2m+1\\) cannot have exactly \\((m+1)(m+2)+1\\) nodes for any \\(m\\ge2\\). Excluding…",
   "date": "2026-09-30",
   "author": "Zhuo Cheng"
  },
  {
   "title": "The exact number of nonconstant positive solutions to the planar isotropic $L_p$ dual Minkowski problem",
   "link": "https://arxiv.org/abs/2609.39636v1",
   "abs": "We determine the exact number, up to rotations, of nonconstant positive $C^2$ solutions to the planar isotropic $L_p$ dual Minkowski problem for every $(p, q) \\in \\mathbb{R}^2$. We obtain a new parametrization of the…",
   "date": "2026-09-30",
   "author": "Guanyu Tao"
  },
  {
   "title": "Assouad type dimensions of generalized affine fractal interpolation functions and their applications",
   "link": "https://arxiv.org/abs/2609.39524v1",
   "abs": "In this article, we investigate the Assouad spectrum and Assouad dimension of graphs of fractal functions generated by generalized affine iterated function systems. We establish upper and lower bounds for the Assouad…",
   "date": "2026-09-30",
   "author": "Aaryan Dharmesh Shah"
  },
  {
   "title": "Flexible discrete translational surfaces",
   "link": "https://arxiv.org/abs/2609.39517v1",
   "abs": "We give a full list of translational nets which flex within their class of discrete surfaces of translation, by reducing the classification problem to the one of flexible complete bipartite frameworks on the sphere, for…",
   "date": "2026-09-30",
   "author": "Georg Nawratil"
  },
  {
   "title": "Stability of Kantorovich potentials via heat kernel regularization",
   "link": "https://arxiv.org/abs/2609.39213v1",
   "abs": "This survey presents heat kernel regularization as a method for quantitative stability of Kantorovich potentials for the quadratic transport cost. We give a complete new heat kernel proof on Heisenberg groups equipped…",
   "date": "2026-09-30",
   "author": "Bang-Xian Han"
  }
 ],
 "代数": [
  {
   "title": "Structure of higher-genus open-closed Gromov--Witten theory of $\\mathcal{O}_{\\mathbb{P}^{1}}(p-1)\\oplus\\mathcal{O}_{\\mathbb{P}^{1}}(-p-1)$",
   "link": "https://arxiv.org/abs/2609.40257v1",
   "abs": "We study the closed and open Gromov--Witten potentials of the toric Calabi--Yau threefold $$ X_p=\\operatorname{Tot}\\bigl(\\mathcal{O}_{\\mathbb{P}^{1}}(p-1)\\oplus\\mathcal{O}_{\\mathbb{P}^{1}}(-p-1)\\bigr),\\qquad p\\geq 2. $$…",
   "date": "2026-09-30",
   "author": "Shuai Guo"
  },
  {
   "title": "A rational surface with discrete and non-finitely generated automorphism group",
   "link": "https://arxiv.org/abs/2609.40045v1",
   "abs": "We construct a smooth complex projective rational surface whose automorphism group is discrete and not finitely generated. It is obtained by blowing up a point on a branch curve of a rational quotient of a product…",
   "date": "2026-09-30",
   "author": "Tien-Cuong Dinh"
  },
  {
   "title": "Matsumura's extension problem for pluricanonical forms in Kähler families I: the smooth and essentially Moishezon cases",
   "link": "https://arxiv.org/abs/2609.40040v1",
   "abs": "In this paper, we study a problem posed by Matsumura on the extension of pluricanonical forms in Kähler families with a relatively nef canonical bundle. We give an affirmative answer in the smooth case, and for…",
   "date": "2026-09-30",
   "author": "Jian Chen"
  },
  {
   "title": "On the quadratic length of plane Cremona maps of degree 4",
   "link": "https://arxiv.org/abs/2609.39943v1",
   "abs": "Every non-linear plane Cremona map can be decomposed into quadratic maps, and the minimum number of quadratic maps required is called its quadratic length. It is known that plane Cremona maps of degree 3 have quadratic…",
   "date": "2026-09-30",
   "author": "Alberto Calabri"
  },
  {
   "title": "Potential isotriviality of isocrystals and proper covers",
   "link": "https://arxiv.org/abs/2609.39815v1",
   "abs": "We study convergent and overconvergent isocrystals that become trivial after pullback along a proper surjective morphism. On a geometrically unibranch variety over an algebraically closed field, every such object is…",
   "date": "2026-09-30",
   "author": "Adrian Langer"
  }
 ],
 "分析": [
  {
   "title": "Resurgent rigidity of mock theta functions: uniqueness and natural boundary crossing",
   "link": "https://arxiv.org/abs/2609.40276v1",
   "abs": "We develop a resurgent transseries approach to mock theta functions and show that the associated Mordell--Appell integrals underlie their modular and resurgent structure. From these integrals, we recover the modular…",
   "date": "2026-09-30",
   "author": "Ovidiu Costin"
  },
  {
   "title": "The Work of Hong Wang",
   "link": "https://arxiv.org/abs/2609.40161v1",
   "abs": "Hong Wang has made several tremendous contributions to harmonic analysis and geometric measure theory. On the 23rd of July 2026, she was awarded the Fields Medal. In this short article we shall focus on her work on the…",
   "date": "2026-09-30",
   "author": "Christopher D. Sogge"
  },
  {
   "title": "A Hartman-Grobman theorem on Banach bundles",
   "link": "https://arxiv.org/abs/2609.40039v1",
   "abs": "We provide generalized linearization theorems for skew-product flows on abstract Banach bundles over locally compact metric spaces, allowing for a unified treatment of uniform and nonuniform, exponential and strong…",
   "date": "2026-09-30",
   "author": "Benjamin Rogoll"
  },
  {
   "title": "More on dominated and microscopic sets",
   "link": "https://arxiv.org/abs/2609.39942v1",
   "abs": "Let $S$ be a family of sequences decreasing to zero. A set $E$ in a metric space is $S$-dominated if, for every $s\\in S$, there exists a countable cover $\\{E_n\\}$ of $E$ such that $diam E_n<s_n$ for every $n$. We…",
   "date": "2026-09-30",
   "author": "Ondřej Zindulka"
  },
  {
   "title": "A stochastic Carleson embedding theorem with constant $e$ and the vector of Riesz transforms",
   "link": "https://arxiv.org/abs/2609.39919v1",
   "abs": "We prove a continuous-time Carleson embedding theorem with constant $e$ for a system of square-integrable continuous martingales whose quadratic covariations mimic the generalised Cauchy--Riemann relations. The argument…",
   "date": "2026-09-30",
   "author": "Komla Domelevo"
  }
 ],
 "概率与统计": [
  {
   "title": "Singularity of harmonic measures for hyperbolic lattices",
   "link": "https://arxiv.org/abs/2609.40357v1",
   "abs": "Let $Γ<\\mathrm{Isom}(\\mathbb H^n)$, $n\\geq2$, be a cocompact lattice containing a convex cocompact codimension-one subgroup in the sense of Sageev. We prove that every finitely supported admissible random walk on $Γ$…",
   "date": "2026-09-30",
   "author": "Nikolay Bogachev"
  },
  {
   "title": "Half-space KPZ equation from a class of nonlinear SPDEs",
   "link": "https://arxiv.org/abs/2609.40352v1",
   "abs": "We derive the half-space KPZ equation as a continuum limit from a general class of Ginzburg-Landau SPDEs under weak nonlinearity scaling. To our knowledge, this is the first half-space universality result for the KPZ…",
   "date": "2026-09-30",
   "author": "Kevin Yang"
  },
  {
   "title": "Gibbs Sampling in the Shattered Phase by Decoded Quantum Interferometry",
   "link": "https://arxiv.org/abs/2609.40345v1",
   "abs": "We apply Decoded Quantum Interferometry (DQI) to sample from the Gibbs measures of classical Ising spin Hamiltonians. We show that this Gibbs sampling problem reduces to a quantum decoding problem, and the temperature…",
   "date": "2026-09-30",
   "author": "Leo Zhou"
  },
  {
   "title": "Spectral theory for dynamical large deviations in non-Markov self-interacting processes",
   "link": "https://arxiv.org/abs/2609.40329v1",
   "abs": "We develop a spectral theory for dynamical large deviations in non-Markov jump processes and non-Markov chains, whose dynamics depends on the past through state- and jump-dependent empirical observables. We demonstrate…",
   "date": "2026-09-30",
   "author": "Francesco Coghi"
  },
  {
   "title": "Refined sample complexities from the tomographic rate function",
   "link": "https://arxiv.org/abs/2609.40271v1",
   "abs": "Protocols for quantum state tomography can be characterized either by their sample complexity or by the tomographic rate function that governs the large deviation behaviour of error estimates. We establish a framework…",
   "date": "2026-09-30",
   "author": "Arick Grootveld"
  }
 ],
 "组合与图论": [
  {
   "title": "The classical limit of the Magnus expansion",
   "link": "https://arxiv.org/abs/2609.40291v1",
   "abs": "We uncover a connection between the classical limit of the Magnus expansion in quantum field theory and the Malvenuto-Reutenauer Hopf algebra of permutations. We study a cubic scalar theory describing a massive particle…",
   "date": "2026-09-30",
   "author": "Andreas Brandhuber"
  },
  {
   "title": "Another proof that the two color bipartite Ramsey number is $O(2^t)$",
   "link": "https://arxiv.org/abs/2609.40288v1",
   "abs": "For positive integers $t$ and $q$ let $b_q(t)$ be the smallest integer $n$ so that any coloring of the edges of the complete bipartite graph $K_{n,n}$ with $q$ colors yields a monochromatic copy of $K_{t,t}$. We give an…",
   "date": "2026-09-30",
   "author": "Yury Person"
  },
  {
   "title": "Classification of prime graphs with 2-switch-degree at most 4",
   "link": "https://arxiv.org/abs/2609.40274v1",
   "abs": "The 2-switch-degree $\\text{deg}(G)$ of a graph $G$ is the number of 2-switches that can be performed on $G$; equivalently, it is the degree of $G$ as a vertex of the realization graph $\\mathcal{G}(d)$ of its degree…",
   "date": "2026-09-30",
   "author": "Victor N. Schvöllner"
  },
  {
   "title": "Submodularity of entropy under quantum convolution",
   "link": "https://arxiv.org/abs/2609.40211v1",
   "abs": "We develop a submodular framework for the von Neumann entropy of discrete quantum convolutions, providing a noncommutative counterpart to the direct side of entropic additive combinatorics. We first introduce globally…",
   "date": "2026-09-30",
   "author": "Milad M. Goodarzi"
  },
  {
   "title": "Positive cubature on $S^2$:low-degree rigidity and uniform bounds",
   "link": "https://arxiv.org/abs/2609.40210v1",
   "abs": "Let \\(N_t\\) denote the least number of nodes in a positive cubature formula of degree \\(t\\) on \\(S^2\\). We prove that a formula of degree \\(2m+1\\) cannot have exactly \\((m+1)(m+2)+1\\) nodes for any \\(m\\ge2\\). Excluding…",
   "date": "2026-09-30",
   "author": "Zhuo Cheng"
  }
 ],
 "线性代数": [
  {
   "title": "Exact sequences of representation categories of weak Hopf algebras",
   "link": "https://arxiv.org/abs/2609.40298v1",
   "abs": "We study exact sequences of representation categories of weak Hopf algebras over an arbitrary field. Given a sequence $A\\overset{k}{\\to} B\\oversetπ{\\to} H$, where $A$ and $B$ are weak Hopf algebras and $H$ is a Hopf…",
   "date": "2026-09-30",
   "author": "Quinn T. Kolt"
  },
  {
   "title": "Discrete differential-geometric Poisson brackets: general theory and explicit constructions",
   "link": "https://arxiv.org/abs/2609.40049v1",
   "abs": "We review the discrete theory of differential-geometric Poisson brackets as introduced by B. A. Dubrovin, and we present a complete proof of their characterisation in the non-degenerate case. We use this…",
   "date": "2026-09-30",
   "author": "Marta Dell'Atti"
  },
  {
   "title": "A Koteljanskii inequality for permanents",
   "link": "https://arxiv.org/abs/2609.39979v1",
   "abs": "We prove a permanental analogue of Koteljanskii's inequality. If $A$ is an inverse $M$-matrix that becomes symmetric after a positive diagonal similarity, then…",
   "date": "2026-09-30",
   "author": "Suvrit Sra"
  },
  {
   "title": "Characterization Results on Generalized Smash Biproduct Hopf Algebras over the Partial Dual Construction",
   "link": "https://arxiv.org/abs/2609.39896v1",
   "abs": "Let $B$ and $D$ be both algebras and coalgebras in a braided monoidal category $\\mathcal{C}$. In the literature, there are equivalent conditions for $(B,D)$ to form a generalized smash biproduct (or cross product)…",
   "date": "2026-09-30",
   "author": "Kangqiao Li"
  },
  {
   "title": "Lattice of 456 semigroup varieties from equations of order up to 4",
   "link": "https://arxiv.org/abs/2609.39872v1",
   "abs": "We consider the 653 equational laws of order up to 4 for an associative binary operation, and all of their conjunctions. We determine that there are only 456 equivalence classes of such conjunctions (associative…",
   "date": "2026-09-30",
   "author": "Bruno Le Floch"
  }
 ],
 "拓扑学": [
  {
   "title": "Double Steinberg coinvariants for special linear groups",
   "link": "https://arxiv.org/abs/2609.39991v1",
   "abs": "For a field $F$ we study the coinvariants for the $SL_n(F)$-action on the double Steinberg module $St_n(F) \\otimes St_n(F)$ and show they have a rich algebraic structure: for $n = 2$ it is the Grothendieck-Witt group of…",
   "date": "2026-09-30",
   "author": "Tatiana Abdelnaim"
  },
  {
   "title": "On the topology of the space of vacuum initial data sets",
   "link": "https://arxiv.org/abs/2609.39987v1",
   "abs": "We show that the space of vacuum initial data sets on a closed manifold often has many non-trivial homotopy groups. The starting point is a result of the second named author, which constructs non-trivial elements in the…",
   "date": "2026-09-30",
   "author": "Romain Gicquaud"
  },
  {
   "title": "A Counterexample to Cohomological Rigidity of Toric Manifolds",
   "link": "https://arxiv.org/abs/2609.39707v1",
   "abs": "We construct two toric manifolds of complex dimension four, which are not homotopy equivalent but have isomorphic integral cohomology rings.",
   "date": "2026-09-30",
   "author": "Tao Gong"
  },
  {
   "title": "Weak, stable, and ordinary Lusternik-Schnirelmann category of finite spaces",
   "link": "https://arxiv.org/abs/2609.39615v1",
   "abs": "The weak, stable, and ordinary Lusternik--Schnirelmann categories of a finite $T_0$-space $X$ satisfy $\\operatorname{cat}_w(X)\\leq \\operatorname{cat}_s(X)\\leq \\operatorname{cat}(X)$. We give a general construction…",
   "date": "2026-09-30",
   "author": "David Mosquera-Lois"
  },
  {
   "title": "T-ARC: Topology-Aware Randomized Clustering via Distributionally Robust Stochastic Block Models",
   "link": "https://arxiv.org/abs/2609.39466v1",
   "abs": "In this work, we introduce a new clustering method, namely T-ARC (Topology-Aware Randomized Clustering), that corrects the geometric bias of K-means by embedding topological information directly into the optimization…",
   "date": "2026-09-30",
   "author": "Serena Grazia De Benedictis"
  }
 ],
 "复分析": [
  {
   "title": "Dynamics of Hyperbolic Schwarz Reflections",
   "link": "https://arxiv.org/abs/2609.40196v1",
   "abs": "We give a conformal mating description for the class $Σ_d$ of hyperbolic Schwarz reflections with connected and full filled Julia set; this parallels the recent development in several non-hyperbolic settings. We show…",
   "date": "2026-09-30",
   "author": "Kirill Lazebnik"
  },
  {
   "title": "Matsumura's extension problem for pluricanonical forms in Kähler families I: the smooth and essentially Moishezon cases",
   "link": "https://arxiv.org/abs/2609.40040v1",
   "abs": "In this paper, we study a problem posed by Matsumura on the extension of pluricanonical forms in Kähler families with a relatively nef canonical bundle. We give an affirmative answer in the smooth case, and for…",
   "date": "2026-09-30",
   "author": "Jian Chen"
  },
  {
   "title": "A Counterexample to the Liu-Luo-Luo Conjecture on the Harmonic Landau Radius",
   "link": "https://arxiv.org/abs/2609.39676v1",
   "abs": "We disprove a conjecture of Liu, Luo, and Luo (2020) concerning the Landau radius for bounded planar harmonic mappings. We construct an explicit harmonic mapping $F_M$ satisfying the standard normalization conditions…",
   "date": "2026-09-30",
   "author": "Mikhail Borovikov"
  },
  {
   "title": "The sharp radius in Korenblum's maximum principle for the Fock space",
   "link": "https://arxiv.org/abs/2609.39622v1",
   "abs": "Korenblum's maximum principle states that if $|f| \\le |g|$ near the boundary, then $\\| f \\| \\le \\| g \\|$. The optimal size of the region of domination has been studied in Bergman spaces since 1991 and in Fock spaces…",
   "date": "2026-09-30",
   "author": "Frank Wikström"
  },
  {
   "title": "Characterization of Sobolev regularity of plurisubharmonic functions",
   "link": "https://arxiv.org/abs/2609.39136v1",
   "abs": "Let $f$ be a nonzero holomorphic germ at $0 \\in \\mathbb C^n$ with $f(0)=0$, and let $χ$ be a $C^2$ non-decreasing convex function on the left half-line. We establish sharp necessary and sufficient conditions for the…",
   "date": "2026-09-30",
   "author": "Hongrong Chen"
  }
 ],
 "微分方程": [
  {
   "title": "Half-space KPZ equation from a class of nonlinear SPDEs",
   "link": "https://arxiv.org/abs/2609.40352v1",
   "abs": "We derive the half-space KPZ equation as a continuum limit from a general class of Ginzburg-Landau SPDEs under weak nonlinearity scaling. To our knowledge, this is the first half-space universality result for the KPZ…",
   "date": "2026-09-30",
   "author": "Kevin Yang"
  },
  {
   "title": "Teukolsky equations in perturbations of Kerr",
   "link": "https://arxiv.org/abs/2609.40315v1",
   "abs": "The Kerr stability conjecture has been proved in the slowly rotating case, i.e., $|a|\\ll m$, in the sequence of works \\cite{KS-GCM1} \\cite{KS-GCM2} \\cite{KS:Kerr} by Sergiu Klainerman and the author, \\cite{GKS22} by…",
   "date": "2026-09-30",
   "author": "Jérémie Szeftel"
  },
  {
   "title": "Hadamard Local Well-Posedness for Compressible Liquids with a Free Surface",
   "link": "https://arxiv.org/abs/2609.40163v1",
   "abs": "We prove local well-posedness in the Hadamard sense for the three-dimensional compressible Euler equations governing a liquid with a free surface and no surface tension. Under the Taylor sign condition and the boundary…",
   "date": "2026-09-30",
   "author": "Tao Luo"
  },
  {
   "title": "Topological invariants for anisotropic quasilinear elliptic systems: A Poincaré-Hopf formula",
   "link": "https://arxiv.org/abs/2609.40145v1",
   "abs": "We consider the functional $I_{δ,Ψ_1,Ψ_2}:X \\to \\mathbb{R}$ defined for any $z=(u,v) \\in X$ as \\begin{align*} I_{δ,Ψ_1,Ψ_2}(z) & = \\int_Ω Ψ_1(\\nabla u) \\, dx + \\int_Ω Ψ_2(\\nabla v ) \\, dx & - \\int_Ω H(δ,x,u(x),v(x))…",
   "date": "2026-09-30",
   "author": "Natalino Borgia"
  },
  {
   "title": "Dispersion for the wave equation with Neumann boundary condition inside general strictly convex domains",
   "link": "https://arxiv.org/abs/2609.40114v1",
   "abs": "We consider the wave equation on a manifold of dimension d>1 with smooth strictly convex boundary, with Neumann boundary condition. We construct a sharp local in time parametrix for the Neumann wave equation near…",
   "date": "2026-09-30",
   "author": "Oana Ivanovici"
  }
 ],
 "博弈论": [
  {
   "title": "ISS and integral ISS coincide for linear systems with bounded inputs",
   "link": "https://arxiv.org/abs/2609.40348v1",
   "abs": "We show that input-to-state stability (ISS) and integral input-to-state stability (integral ISS) with respect to the space of essentially bounded functions are equivalent properties for linear systems. The proof…",
   "date": "2026-09-30",
   "author": "Sahiba Arora"
  },
  {
   "title": "Open Capacity Pooling in Agentic Supply Chains: Coordination-Directed LLM Discovery and Distributed Re-optimization",
   "link": "https://arxiv.org/abs/2609.40296v1",
   "abs": "Disruptions can exhaust a supply chain network's capacity, yet outside capacity is hard to use: incumbent models are private, provider profiles are unstructured, and offers stay hidden until costly engagement. We…",
   "date": "2026-09-30",
   "author": "Yujia Xu"
  },
  {
   "title": "Nonlinear Trajectory Optimization Models for Uncrewed Aerial Vehicles with Mobile Charging Support",
   "link": "https://arxiv.org/abs/2609.40201v1",
   "abs": "Supporting Uncrewed Aerial Vehicles (UAVs) with mobile charging stations enables persistent UAV autonomy in infrastructure-sparse environments. In this setting, trajectory optimization for UAVs is challenging because it…",
   "date": "2026-09-30",
   "author": "Minsen Yuan"
  },
  {
   "title": "EndoWake: Modeling Wind by Linear Programming for Wind Farm Layout Optimization",
   "link": "https://arxiv.org/abs/2609.40157v1",
   "abs": "The Wind Farm Layout Optimization problem consists of placing a given number of turbines within a given area so as to maximize energy production. One of its main challenges is the wake effect between turbines, which can…",
   "date": "2026-09-30",
   "author": "Martina Fischetti"
  },
  {
   "title": "Policy Iteration Is Not Strongly Polynomial for Deterministic Markov Decision Processes: The Price of Algorithmic Anarchy",
   "link": "https://arxiv.org/abs/2609.40147v1",
   "abs": "We establish an exponential iteration lower bound in the number of states for Howard's policy iteration on deterministic discounted Markov decision processes, with at most two actions per state. This rules out strong…",
   "date": "2026-09-30",
   "author": "Han Zhong"
  }
 ],
 "数理逻辑": [
  {
   "title": "PAC fields and difference fields with generic automorphisms",
   "link": "https://arxiv.org/abs/2609.40251v1",
   "abs": "We study the existence of model companions after adjoining an automorphism to field theories in two complementary settings. For bounded PAC fields of characteristic zero containing all roots of unity and admitting a…",
   "date": "2026-09-30",
   "author": "Özlem Beyarslan"
  },
  {
   "title": "Lattice of 456 semigroup varieties from equations of order up to 4",
   "link": "https://arxiv.org/abs/2609.39872v1",
   "abs": "We consider the 653 equational laws of order up to 4 for an associative binary operation, and all of their conjunctions. We determine that there are only 456 equivalence classes of such conjunctions (associative…",
   "date": "2026-09-30",
   "author": "Bruno Le Floch"
  },
  {
   "title": "Continuous graph homomorphisms of higher dimensional abelian group actions",
   "link": "https://arxiv.org/abs/2609.39824v1",
   "abs": "For every fixed integer $d\\geq2$, we prove that the finite graphs receiving a continuous homomorphism from the standard Schreier graph $F(2^{\\mathbb Z^d})$ form a $Σ^0_1$-complete set. This extends a theorem of Gao…",
   "date": "2026-09-30",
   "author": "Ruijun Wang"
  },
  {
   "title": "Non-finite Axiomatizability and Undecidability of $\\mathsf{Cheq}$",
   "link": "https://arxiv.org/abs/2609.39577v1",
   "abs": "We prove that $\\mathsf{Cheq}$ is not finitely axiomatizable, resolving a longstanding open problem in intermediate and modal logics. We further prove that the undecidability of Medvedev logic implies the undecidability…",
   "date": "2026-09-30",
   "author": "Han Xiao"
  },
  {
   "title": "Hagendorf Orders",
   "link": "https://arxiv.org/abs/2609.39487v1",
   "abs": "Call a linear order type $\\varphi$ Hagendorf if it shares two properties with additively indecomposable ordinal numbers without being one itself: $\\varphi$ is strictly indecomposable to the right and whenever…",
   "date": "2026-09-30",
   "author": "Jonathan Schilhan"
  }
 ]
};
