/* 由 LBLB 数学前沿更新器自动生成：各主题最新论文（arXiv 优先，Semantic Scholar 备用）。请勿手动编辑。 */
window.LBLB_PAPERS = {
 "数论": [
  {
   "title": "Galois groups of twisted reciprocal polynomials: a uniform asymptotic",
   "link": "https://arxiv.org/abs/2609.31613v1",
   "abs": "We study the Galois group $G_f$ of a random polynomial $f$ in the family of polynomials of degree $2n$ satisfying the twisted reciprocal relation $f(x) = x^{2n}/b^n \\cdot f(b/x)$. We use a Euclidean height adapted to…",
   "date": "2026-09-25",
   "author": "Evan M. O'Dorney"
  },
  {
   "title": "Formal groups and $(\\varphi,Γ)$-modules",
   "link": "https://arxiv.org/abs/2609.31608v1",
   "abs": "Let $K/E$ be a finite unramified extension of $p$-adic local fields, and let $H$ be a one-dimensional formal $\\mathcal{O}_E$-module of finite height over $\\mathcal{O}_K$. We introduce the exponential period map of $H$…",
   "date": "2026-09-25",
   "author": "Daishi Kiyohara"
  },
  {
   "title": "Galois groups of integer polynomials with prescribed coefficients",
   "link": "https://arxiv.org/abs/2609.31597v1",
   "abs": "Fix a degree $n$, a nonzero integer constant term, and some further coefficients of a monic integer polynomial, leaving $s$ coefficients to vary in $[-H,H]$. We first prove that, when only the leading and constant…",
   "date": "2026-09-25",
   "author": "Evan M. O'Dorney"
  },
  {
   "title": "Free semigroups of power series",
   "link": "https://arxiv.org/abs/2609.31582v1",
   "abs": "Given power series $f_1,\\dots,f_r\\in z^2K[[z]]$ over a field of characteristic zero, we show that the semigroup $\\langle f_1,\\dots,f_r\\rangle$ generated by the $f$'s under composition is free of rank $r$ whenever the…",
   "date": "2026-09-25",
   "author": "Wade Hindes"
  },
  {
   "title": "On the infinite sum of reciprocals of the fourth powers of balancing numbers",
   "link": "https://arxiv.org/abs/2609.31548v1",
   "abs": "In this note, we study the infinite reciprocal sum $\\sum_{k=n}^{\\infty}1/B_k^4$ involving the fourth powers of balancing numbers $B_n$. We show that, for every $n\\geq2$, \\begin{equation*} \\left\\lfloor \\left(…",
   "date": "2026-09-25",
   "author": "Subhasis Panda"
  }
 ],
 "几何": [
  {
   "title": "Unbalancing unit vectors",
   "link": "https://arxiv.org/abs/2609.31389v1",
   "abs": "We show that for every $n$ unit vectors $v_1, \\dots, v_n$ in the $d$-dimensional Euclidean space, there exist signs $\\varepsilon_1, \\dots, \\varepsilon_n \\in \\{\\pm 1\\}$ such that…",
   "date": "2026-09-25",
   "author": "Zilin Jiang"
  },
  {
   "title": "Semilinear Neumann boundary value problems for measure-valued maps",
   "link": "https://arxiv.org/abs/2609.31353v1",
   "abs": "We study the Wasserstein lift of nonlinear Poisson systems with inhomogeneous Neumann boundary conditions. We establish the existence of minimizers using new estimates involving the $p$-moments of measure-valued traces.…",
   "date": "2026-09-25",
   "author": "Aleksei Kroshnin"
  },
  {
   "title": "Bellman's Forest Problem and Computability",
   "link": "https://arxiv.org/abs/2609.31352v1",
   "abs": "The goal of this paper is to refine methods in computable analysis and to employ them in the study of solutions of an optimization problem posed by Bellman. This problem asks how to find optimal (shortest) paths which…",
   "date": "2026-09-25",
   "author": "Jacob Canel"
  },
  {
   "title": "The number of touching pairs of congruent sphere packings in Euclidean 3-space",
   "link": "https://arxiv.org/abs/2609.31331v1",
   "abs": "A packing of $n$ congruent balls in $\\mathbb{R}^3$ is a family of interior-disjoint Euclidean balls all having the same radius. The contact number of a packing is the number of touching pairs of balls. In this paper we…",
   "date": "2026-09-25",
   "author": "Cameron Strachan"
  },
  {
   "title": "An elementary solution to the polarization problem",
   "link": "https://arxiv.org/abs/2609.31124v1",
   "abs": "By distilling and combining the ideas of previous arguments, we provide a self-contained and entirely elementary proof of the strong and linear polarization problems.",
   "date": "2026-09-25",
   "author": "Gergely Ambrus"
  }
 ],
 "代数": [
  {
   "title": "Formal groups and $(\\varphi,Γ)$-modules",
   "link": "https://arxiv.org/abs/2609.31608v1",
   "abs": "Let $K/E$ be a finite unramified extension of $p$-adic local fields, and let $H$ be a one-dimensional formal $\\mathcal{O}_E$-module of finite height over $\\mathcal{O}_K$. We introduce the exponential period map of $H$…",
   "date": "2026-09-25",
   "author": "Daishi Kiyohara"
  },
  {
   "title": "Fourier duality on compactified Prym fibrations",
   "link": "https://arxiv.org/abs/2609.31604v1",
   "abs": "We study Fourier-Mukai duality for a class of compactified Prym fibrations including moduli spaces of $\\mathrm{SL}$ Higgs bundles over the elliptic locus. This leads to a shadow of the Hausel-Thaddeus conjecture, proof…",
   "date": "2026-09-25",
   "author": "Anne Larsen"
  },
  {
   "title": "Completely monotone negative powers of hyperbolic polynomials",
   "link": "https://arxiv.org/abs/2609.31592v1",
   "abs": "Scott and Sokal asked whether every homogeneous polynomial with the half-plane property has a completely monotone negative power. We show that it does, and prove the positivity conjectures of…",
   "date": "2026-09-25",
   "author": "Dongsheng Wei"
  },
  {
   "title": "Profinite Non-Rigidity of Arithmetic Lattices and the Kähler Property",
   "link": "https://arxiv.org/abs/2609.31523v1",
   "abs": "We study the profinite non-rigidity of arithmetic lattices and its implications for the Kähler property. In the first part, we characterize the absolute Dynkin types that admit non-isomorphic real forms of higher-rank…",
   "date": "2026-09-25",
   "author": "Yukun Du"
  },
  {
   "title": "Teichmüller and moduli spaces for complex nilmanifolds",
   "link": "https://arxiv.org/abs/2609.31516v1",
   "abs": "We develop several tools to study the local and global structure of the Teichmüller and moduli spaces for complex nilmanifolds. As a starting point, we prove a structure theorem for holomorphic maps between complex…",
   "date": "2026-09-25",
   "author": "Konstantin Wehler"
  }
 ],
 "分析": [
  {
   "title": "Prescribed projections for a general class of maps and efficient covering by variable plane curves",
   "link": "https://arxiv.org/abs/2609.31602v1",
   "abs": "We prove a prescribed projection theorem for any class of non-linear projections defined on open subsets of the plane which satisfies some mild geometric conditions. This generalizes Davies's classic result on…",
   "date": "2026-09-25",
   "author": "Alan Chang"
  },
  {
   "title": "Completely monotone negative powers of hyperbolic polynomials",
   "link": "https://arxiv.org/abs/2609.31592v1",
   "abs": "Scott and Sokal asked whether every homogeneous polynomial with the half-plane property has a completely monotone negative power. We show that it does, and prove the positivity conjectures of…",
   "date": "2026-09-25",
   "author": "Dongsheng Wei"
  },
  {
   "title": "Optimal stability hierarchies of the Heisenberg Uncertainty Principle for solenoidal fields and of the second order Caffarelli--Kohn--Nirenberg inequalities",
   "link": "https://arxiv.org/abs/2609.31579v1",
   "abs": "In 2018, V. Maz'ya proposed 75 open problems in analysis and PDEs. One of them is about the best constant for the Heisenberg Uncertainty Principle for solenoidal vector fields motivated by questions in hydrodynamics.…",
   "date": "2026-09-25",
   "author": "Anh Do"
  },
  {
   "title": "Sharp weighted weak-type bounds for commutators of singular integrals",
   "link": "https://arxiv.org/abs/2609.31493v1",
   "abs": "We establish sharp weak-type bounds for commutators of Calderón--Zygmund operators and $\\text{BMO}(\\mathbb{R}^n)$ symbols with respect to $A_p$ weights. We prove that the bound \\looseness=-1 $$…",
   "date": "2026-09-25",
   "author": "Adam Mair"
  },
  {
   "title": "The Wiener norm of lifts of dense Sidon sets",
   "link": "https://arxiv.org/abs/2609.31335v1",
   "abs": "We describe, with proof, an infinite class of examples of finite sets of integers $A$ for which $\\|\\widehat{1_A}\\|_1\\geq (c_\\mathcal{R}-o_{|A| \\rightarrow \\infty}(1))\\sqrt{|A|}$ where $c_\\mathcal{R}=0.953\\dots$.",
   "date": "2026-09-25",
   "author": "Tom Sanders"
  }
 ],
 "概率与统计": [
  {
   "title": "Algorithmic trading and stochastic integration",
   "link": "https://arxiv.org/abs/2609.31578v1",
   "abs": "We study simple predictable processes whose coefficients are represented by neural networks. On finite measure spaces, we establish density results for neural networks in Orlicz spaces. For filtrations generated by a…",
   "date": "2026-09-25",
   "author": "Aleksandar Arandjelovic"
  },
  {
   "title": "Singular Backward SDEs for Optimal Control with State Constraints",
   "link": "https://arxiv.org/abs/2609.31487v1",
   "abs": "We investigate a class of backward stochastic differential equations (BSDEs) with at most quadratic growth which explode at a possibly unbounded random horizon, defined through the first hitting of zero of an adapted…",
   "date": "2026-09-25",
   "author": "Mathieu Lise"
  },
  {
   "title": "Anatomical Connectivity from Tractography-free Diffusion Tensor Imaging and Its Application to EEG Brain Imagin",
   "link": "https://arxiv.org/abs/2609.31410v1",
   "abs": "This proof-of-concept paper demonstrates how the Kalman filter, as a brain imaging method, can be enhanced by incorporating raw diffusion tensor imaging (DTI) data without tractography, in addition to EEG recordings. An…",
   "date": "2026-09-25",
   "author": "Joonas Lahtinen"
  },
  {
   "title": "Convergence of a fully discrete approximation for the stochastic 2D Euler equations with Kraichnan transport noise",
   "link": "https://arxiv.org/abs/2609.31369v1",
   "abs": "We study a fully discrete approximation theory for the two-dimensional incompressible Euler equations on $\\mathbb{T}^{2}$, in vorticity form, driven by Kraichnan-type transport noise and with…",
   "date": "2026-09-25",
   "author": "Abhishek Chaudhary"
  },
  {
   "title": "Semilinear Neumann boundary value problems for measure-valued maps",
   "link": "https://arxiv.org/abs/2609.31353v1",
   "abs": "We study the Wasserstein lift of nonlinear Poisson systems with inhomogeneous Neumann boundary conditions. We establish the existence of minimizers using new estimates involving the $p$-moments of measure-valued traces.…",
   "date": "2026-09-25",
   "author": "Aleksei Kroshnin"
  }
 ],
 "组合与图论": [
  {
   "title": "Completely monotone negative powers of hyperbolic polynomials",
   "link": "https://arxiv.org/abs/2609.31592v1",
   "abs": "Scott and Sokal asked whether every homogeneous polynomial with the half-plane property has a completely monotone negative power. We show that it does, and prove the positivity conjectures of…",
   "date": "2026-09-25",
   "author": "Dongsheng Wei"
  },
  {
   "title": "2-colouring shift-chains",
   "link": "https://arxiv.org/abs/2609.31549v1",
   "abs": "A shift-chain is an $ r $-uniform hypergraph $ \\mathcal{H} $ on vertex set $ [n] $ with the property that, for any two edges $ \\{ e_1, \\ldots, e_r \\} $ and $ \\{ f_1, \\ldots, f_r \\} $ with $ e_1 < \\cdots < e_r $ and…",
   "date": "2026-09-25",
   "author": "Zak Smith"
  },
  {
   "title": "How large can $B_n$- and $D_n$-friezes be?",
   "link": "https://arxiv.org/abs/2609.31537v1",
   "abs": "We pin down the largest entries possible in positive integral friezes of types $D_n$ for $n\\geq 4$ and $B_n$ for $n\\geq 2$, addressing a conjecture of Robin Zhang. For type $D_n$, the sharp upper bound is…",
   "date": "2026-09-25",
   "author": "Florian Ito Sprung"
  },
  {
   "title": "Discounted Hitting Domination on Graphs with Submodularity, Complexity and Exact Algorithms",
   "link": "https://arxiv.org/abs/2609.31535v1",
   "abs": "On a network with a fixed set of verified sources, discounted averaging induces an equilibrium support $h_i^S=\\mathbb{E}_i[λ^{T_S}]$, the discounted probability that a random walk reaches $S$ before attenuation. We…",
   "date": "2026-09-25",
   "author": "Julian D. Allagan"
  },
  {
   "title": "Irreducible rootless unimodular lattices generated by vectors of norm $3$",
   "link": "https://arxiv.org/abs/2609.31478v1",
   "abs": "The classical ADE classification implies that $E_8$ is the unique irreducible unimodular Euclidean lattice generated by vectors of norm $2$. In sharp contrast, for every positive integer $m$, we construct an irreducible…",
   "date": "2026-09-25",
   "author": "Hong-Jun Ge"
  }
 ],
 "线性代数": [
  {
   "title": "The Hilbert Basis Theorem for Non-Associative Skew Power Series Rings and Non-Associative Skew Laurent Series Rings over a Non-Associative Coefficient Ring",
   "link": "https://arxiv.org/abs/2609.31486v1",
   "abs": "In this paper, we give conditions on a unital non-associative ring $R$ and additive map $σ: R\\longrightarrow R$ so that the non-associative skew power series ring, denoted by $R[[X;σ]]$ and the non-associative skew…",
   "date": "2026-09-25",
   "author": "Darwin P. Mangubat"
  },
  {
   "title": "Boolean Trusses as Rectangular Bands and Boolean Rings",
   "link": "https://arxiv.org/abs/2609.31051v1",
   "abs": "We introduce Boolean trusses, that is, trusses in which every element is idempotent. Every Boolean truss admits a decomposition into a truss arising from a Boolean ring and a rectangular truss. Furthermore, we classify…",
   "date": "2026-09-25",
   "author": "Ryszard R. Andruszkiewicz"
  },
  {
   "title": "Asymptotic completions of preordered semirings",
   "link": "https://arxiv.org/abs/2609.31021v1",
   "abs": "The study of preordered semirings is motivated by applications in computer science, graph theory, and information theory, and provides tools for understanding the asymptotic preorder, which compares large powers of a…",
   "date": "2026-09-25",
   "author": "Péter Vrana"
  },
  {
   "title": "Fast factorization in diagram monoids",
   "link": "https://arxiv.org/abs/2609.30804v1",
   "abs": "We give explicit algorithms that factor elements of the standard diagram monoids into their usual generators. These algorithms generalize sorting from permutations to partial matchings and set partitions. In every case…",
   "date": "2026-09-25",
   "author": "Matthias Fresacher"
  },
  {
   "title": "Quasi-equivalence of relabeled positroid cluster structures",
   "link": "https://arxiv.org/abs/2609.30637v1",
   "abs": "We prove the Fraser--Sherman-Bennett conjecture on the quasi-equivalence of positroid cluster structures arising from admissibly relabeled plabic graphs. We construct a tilting module from the boundary necklace and…",
   "date": "2026-09-24",
   "author": "Yilin Wu"
  }
 ],
 "拓扑学": [
  {
   "title": "LandscapeSHAP: Which Persistent Homology Class Gets the Credit?",
   "link": "https://arxiv.org/abs/2609.31469v1",
   "abs": "Shapley values, a solution concept from cooperative game theory, have recently become a standard tool for feature credit allocation in machine learning. They provide an axiomatically justified method to fairly…",
   "date": "2026-09-25",
   "author": "Nikola Milićević"
  },
  {
   "title": "Metastable homotopy theory via Tate coalgebras",
   "link": "https://arxiv.org/abs/2609.31274v1",
   "abs": "We develop foundations for metastable homotopy theory using Heuts' 2-truncated Tate coalgebras.",
   "date": "2026-09-25",
   "author": "Marco Nervo"
  },
  {
   "title": "An abelian model for the Goodwillie tower of the circle",
   "link": "https://arxiv.org/abs/2609.31269v1",
   "abs": "We study the Goodwillie tower of the identity evaluated at the circle. Our main result is the p-local equivalence $ΩP_{p^k}I(S^1) \\simeq \\mathbb{Z} \\times Ω^{\\infty+2k}τ_{>0}\\mathbb{Sp}^{p^k}$ obtained from the work of…",
   "date": "2026-09-25",
   "author": "Marco Nervo"
  },
  {
   "title": "A derived Chouinard's theorem for infinite groups",
   "link": "https://arxiv.org/abs/2609.31030v1",
   "abs": "We establish a Chouinard-type theorem for modules over algebras of cochains on the classifying spaces of a broad class of infinite groups, allowing commutative ring spectra as coefficients. We then use this result to…",
   "date": "2026-09-25",
   "author": "Natàlia Castellana"
  },
  {
   "title": "The homology of $\\mathrm{Out}(F_8)$ and $\\mathrm{Aut}(F_7)$",
   "link": "https://arxiv.org/abs/2609.30872v1",
   "abs": "We compute the rational homology of $\\mathrm{Out}(F_8)$ and $\\mathrm{Aut}(F_7)$, and several related groups. We also show that the Eisenstein classes in $H_7(\\mathrm{Aut}(F_5))$ and $H_{11}(\\mathrm{Aut}(F_7))$ are zero.",
   "date": "2026-09-25",
   "author": "Maroš Grego"
  }
 ],
 "复分析": [
  {
   "title": "Teichmüller and moduli spaces for complex nilmanifolds",
   "link": "https://arxiv.org/abs/2609.31516v1",
   "abs": "We develop several tools to study the local and global structure of the Teichmüller and moduli spaces for complex nilmanifolds. As a starting point, we prove a structure theorem for holomorphic maps between complex…",
   "date": "2026-09-25",
   "author": "Konstantin Wehler"
  },
  {
   "title": "Non-autonomous dynamics of inner functions: mixing and entropy",
   "link": "https://arxiv.org/abs/2609.31476v1",
   "abs": "We generalise a mixing result due to Pommerenke for non-autonomous dynamical systems of forward compositions of the boundary values of centred inner functions; the proof depends on a precise bound on the orbits of such…",
   "date": "2026-09-25",
   "author": "Vasiliki Evdoridou"
  },
  {
   "title": "A Criterion for the Sphericity of a CR Manifold",
   "link": "https://arxiv.org/abs/2609.31385v1",
   "abs": "We formulate and prove a simple criterion for the sphericity of a CR manifold (that is, for its equivalence to its model surface). We discuss the differences between the general case, in which the model surface is…",
   "date": "2026-09-25",
   "author": "M. A. Stepanova"
  },
  {
   "title": "Koebe uniformization, John domains, and transboundary modulus",
   "link": "https://arxiv.org/abs/2609.31216v1",
   "abs": "We prove Koebe's conjecture for John domains by showing that every planar John domain is conformally equivalent to a circle domain. Our proof is based on a geometric property of John domains, which we prove to be…",
   "date": "2026-09-25",
   "author": "Christina Karafyllia"
  },
  {
   "title": "An all-dimensional Lewy theorem for pluriharmonic mappings via Milnor monodromy",
   "link": "https://arxiv.org/abs/2609.31212v1",
   "abs": "Hengartner asked whether a pluriharmonic mapping between equidimensional complex Euclidean domains is locally one-to-one precisely at the points where its real Jacobian is nonzero. Naser had earlier claimed the…",
   "date": "2026-09-25",
   "author": "Deguang Zhong"
  }
 ],
 "微分方程": [
  {
   "title": "Singularity models for the Bernoulli free boundary problem from isoparametric hypersurfaces",
   "link": "https://arxiv.org/abs/2609.31617v1",
   "abs": "We develop a general construction of homogeneous solutions to the Bernoulli free boundary problem, as well as general extremal domains on the sphere, from isoparametric foliations of the sphere. Our construction…",
   "date": "2026-09-25",
   "author": "Benjy Firester"
  },
  {
   "title": "Optimal regularity for the arrival time equation",
   "link": "https://arxiv.org/abs/2609.31610v1",
   "abs": "For a convex mean curvature flow in $\\mathbb{R}^{n+1}$, the corresponding arrival time function solves a degenerate elliptic equation that becomes singular at extinction. We prove that it is $C^{24,α}$ for any $0<α<1$…",
   "date": "2026-09-25",
   "author": "Yiqi Huang"
  },
  {
   "title": "General regularity obstructions for the arrival time equation",
   "link": "https://arxiv.org/abs/2609.31599v1",
   "abs": "We study the regularity of the arrival time function associated with mean curvature flow, formulated as a degenerate elliptic equation encoding the singular structure of the flow. We identify a systematic mechanism…",
   "date": "2026-09-25",
   "author": "Yiqi Huang"
  },
  {
   "title": "Optimal stability hierarchies of the Heisenberg Uncertainty Principle for solenoidal fields and of the second order Caffarelli--Kohn--Nirenberg inequalities",
   "link": "https://arxiv.org/abs/2609.31579v1",
   "abs": "In 2018, V. Maz'ya proposed 75 open problems in analysis and PDEs. One of them is about the best constant for the Heisenberg Uncertainty Principle for solenoidal vector fields motivated by questions in hydrodynamics.…",
   "date": "2026-09-25",
   "author": "Anh Do"
  },
  {
   "title": "Asymptotic Behavior of One-Dimensional Hartree Equations with the Long-Range Interaction",
   "link": "https://arxiv.org/abs/2609.31515v1",
   "abs": "We investigate the long-time behavior of small solutions to the one-dimensional Hartree equation with the soft Coulomb interaction. The Hartree equation arises as an effective mean-field model for the evolution of…",
   "date": "2026-09-25",
   "author": "Changhun Yang"
  }
 ],
 "博弈论": [
  {
   "title": "No Universal Remainder Rate for Chambolle-Dossal Acceleration",
   "link": "https://arxiv.org/abs/2609.31557v1",
   "abs": "Chambolle-Dossal acceleration guarantees $F(x_n)-F^*=o(n^{-2})$ for every fixed smooth convex loss with a minimizer. We show that this qualitative improvement admits no universal quantitative rate. For every damping…",
   "date": "2026-09-25",
   "author": "Yuchen Yang"
  },
  {
   "title": "Discounted Hitting Domination on Graphs with Submodularity, Complexity and Exact Algorithms",
   "link": "https://arxiv.org/abs/2609.31535v1",
   "abs": "On a network with a fixed set of verified sources, discounted averaging induces an equilibrium support $h_i^S=\\mathbb{E}_i[λ^{T_S}]$, the discounted probability that a random walk reaches $S$ before attenuation. We…",
   "date": "2026-09-25",
   "author": "Julian D. Allagan"
  },
  {
   "title": "Singular Backward SDEs for Optimal Control with State Constraints",
   "link": "https://arxiv.org/abs/2609.31487v1",
   "abs": "We investigate a class of backward stochastic differential equations (BSDEs) with at most quadratic growth which explode at a possibly unbounded random horizon, defined through the first hitting of zero of an adapted…",
   "date": "2026-09-25",
   "author": "Mathieu Lise"
  },
  {
   "title": "Beyond Empirical Support: Structured Outlier Generation via Sinkhorn Optimal Transport",
   "link": "https://arxiv.org/abs/2609.31470v1",
   "abs": "Outliers are essential for evaluating and improving the robustness of machine learning systems, especially when future distributions may differ significantly from historical training data. In high-stakes applications…",
   "date": "2026-09-25",
   "author": "Haixiang Sun"
  },
  {
   "title": "Network Flexibility Design Under Endogenous Uncertainty",
   "link": "https://arxiv.org/abs/2609.31420v1",
   "abs": "Manufacturing firms face uncertainty in both supply and demand. They implement process flexibility, enabling plants to produce multiple products, to hedge against supply--demand mismatches. Assigning more products to a…",
   "date": "2026-09-25",
   "author": "Soroush Fatemi-Anaraki"
  }
 ],
 "数理逻辑": [
  {
   "title": "Geometric morphisms of virtual ultracategories",
   "link": "https://arxiv.org/abs/2609.31445v1",
   "abs": "We build on the recent development that toposes with enough points can be represented as categories of points equipped with ultraconvergence data (a.k.a. virtual ultracategories), characterizing usual classes of…",
   "date": "2026-09-25",
   "author": "Saadia Gabriel"
  },
  {
   "title": "Bellman's Forest Problem and Computability",
   "link": "https://arxiv.org/abs/2609.31352v1",
   "abs": "The goal of this paper is to refine methods in computable analysis and to employ them in the study of solutions of an optimization problem posed by Bellman. This problem asks how to find optimal (shortest) paths which…",
   "date": "2026-09-25",
   "author": "Jacob Canel"
  },
  {
   "title": "Generalized Quantifiers: Scope Dominance and Branching",
   "link": "https://arxiv.org/abs/2609.31243v1",
   "abs": "Let $P$ and $Q$ be proper upward monotone unary generalized quantifiers on a fixed domain $D$. We study the validity, over all structures $M$ with domain $D$, of \\[ M \\models Px\\,Qy\\,R(x,y) \\rightarrow Qy\\,Px\\,R(x,y)…",
   "date": "2026-09-25",
   "author": "Fredrik Engström"
  },
  {
   "title": "Existence of a Model Companion for Groups of Exponent 3",
   "link": "https://arxiv.org/abs/2609.30061v1",
   "abs": "In this article, we prove that the theory $T_3$ of groups of exponent $3$ has a model companion. Previous work established the existence of model companions for theories of groups of fixed finite exponent and nilpotency…",
   "date": "2026-09-24",
   "author": "Yawara Ishida"
  },
  {
   "title": "Two applications of the point-free coderivative",
   "link": "https://arxiv.org/abs/2609.29436v1",
   "abs": "We present two new applications of Simmons' point-free Cantor-Bendixson coderivative operator in intuitionistic logic. First, we use it to give a simplified proof of the recent result of Xu and Ye that the free Heyting…",
   "date": "2026-09-24",
   "author": "Zoltan A. Kocsis"
  }
 ]
};
